spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/light?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
mybatis-plus:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.vip.light.domain.entity
